spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security-j?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/static/
  jpa:
    database: mysql
    database-platform: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect