server:
  port: 8088
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/spring-secutiry-b?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      password: root
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: org.zhouhy.springsecurity.domain
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org.zhouhy.springsecurity: debug
heima:
  config:
    pubKeyPath: D:\\auth_key\\rsa_key.pub
