server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-secutiry-b?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
mybatis:
  type-aliases-package: org.zhouhy.springsecurity.domain
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.itheima: debug